{{- if .Values.allInOne.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "jaeger.query.name" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: all-in-one
spec:
  ingressClassName: nginx
  rules:
  - host: jaeger.gdixon.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "jaeger.query.name" . }}
            port:
              number: 16686
  tls:
  - hosts:
    - jaeger.gdixon.io
    secretName: your-certificate-name              
{{- end -}}
